### ISSUE TITLE
Falta imagen

### ISSUE THREAD

**Issue by sebacea** [CynthiaEspinola/Hito1_G.E#1]
En esta línea hay referenciada una imagen que no está cargada en el repositorio

https://github.com/CynthiaEspinola/Hito1_G.E/blob/b4e013f3a969fa9728cb72c684f7fc755e6b490a/PautaControles.qmd#L179

**Comment by CynthiaEspinola** [comment]
![Captura de pantalla 2023-11-12 111629](https://github.com/CynthiaEspinola/Hito1_G.E/assets/146403758/d46553cd-15a0-4dc6-b6c5-3f4b9ed380c4)
![Captura de pantalla 2023-11-12 111629](https://github.com/CynthiaEspinola/Hito1_G.E/assets/146403758/92796292-cfcf-4364-a416-c2e9f3dee516)
